from app.models import db, Spot, environment, SCHEMA
import datetime

spots = [
   Spot(
        address="provide later",
        city="Aguanga",
        state="California",
        country="United States",
        name="Off-grid Desert Retreat: Casa Rosada",
        price=175.0,
        preview_img="https://a0.muscache.com/im/pictures/miso/Hosting-48511845/original/8f81a33d-bf66-4976-89f5-a247f0051f3a.jpeg?im_w=960",
        tags="entire place",
        userId=1,
        guests=3,
        bedroom=1,
        beds=3,
        bath=1,
        type="camping",
        clean_fee=5,
        service_fee=15,
        created=datetime.datetime(2022, 9, 20)
    ),
    Spot(
        address="provide later",
        city="Lake Arrowhead",
        state="California",
        country="United States",
        name="Designer A-Frame Cabin in the Trees",
        price=249,
        preview_img="https://a0.muscache.com/im/pictures/miso/Hosting-582573931021615910/original/5e56aff5-969c-4994-aab5-fc0d6b8a2b33.jpeg?im_w=960",
        tags="tiny cabin",
        userId=2,
        guests=6,
        bedroom=3,
        beds=4,
        bath=2,
        type="cabin",
        clean_fee=15,
        service_fee=2,
        created=datetime.datetime(2022, 9, 20)
    ),
    Spot(
        address="provide later",
        city="Malibu",
        state="California",
        country="United States",
        name="Malibu, Carbon Beach- Bungalow Twelve",
        price=566,
        preview_img="https://a0.muscache.com/im/pictures/8d10928e-d1d8-403b-9571-908fbe84baaa.jpg?im_w=960",
        tags="entire house",
        userId=3,
        guests=4,
        bedroom=1,
        beds=2,
        bath=1,
        type="amazing views",
        clean_fee=1,
        service_fee=18,
        created=datetime.datetime(2022, 9, 20)
    )

]

camping = [
    Spot(
        address="provide later",
        city="Joshua Tree",
        state="California",
        country="United States",
        name="Joshua Tree Desert Retreat: Hot Tub, Game Room, National Park, Hammocks",
        price=373,
        preview_img="https://a0.muscache.com/im/pictures/5ce4fbd4-d7e4-49d9-90f2-57cec4025c78.jpg?im_w=960",
        tags="entire place",
        userId=1,
        guests=8,
        bedroom=4,
        beds=4,
        bath=2,
        type="camping",
        clean_fee=8,
        service_fee=15,
        created=datetime.datetime(2022, 9, 20)
    ),
    Spot(
        address="provide later",
        city="Joshua Tree",
        state="California",
        country="United States",
        name="Casa Pequena - Ultimate Camping Vibes, Views",
        price=189,
        preview_img="https://a0.muscache.com/im/pictures/5aac9457-55cc-4f9a-a084-b05dca92b44f.jpg?im_w=720",
        tags="entire place",
        userId=1,
        guests=4,
        bedroom=1,
        beds=2,
        bath=1,
        type="camping",
        clean_fee=2,
        service_fee=12,
        created=datetime.datetime(2022, 9, 20)
    ),
    Spot(
        address="provide later",
        city="Joshua Tree",
        state="California",
        country="United States",
        name="Modern Airstream near Joshua Tree National Park",
        price=185,
        preview_img="https://a0.muscache.com/im/pictures/2bbf0139-1c38-4501-8cfa-d05999ad6871.jpg?im_w=720",
        tags="entire place",
        userId=1,
        guests=2,
        bedroom=1,
        beds=1,
        bath=1,
        type="camping",
        clean_fee=7,
        service_fee=13,
        created=datetime.datetime(2022, 8, 20)
    ),
    Spot(
        address="provide later",
        city="Joshua Tree",
        state="California",
        country="United States",
        name="Joshua Tree Desert Retreat: Hot Tub, Game Room, National Park, Hammocks",
        price=373,
        preview_img="https://a0.muscache.com/im/pictures/0d6047be-29e8-41e6-85e7-c81be50c32c9.jpg?im_w=720",
        tags="entire home",
        userId=1,
        guests=8,
        bedroom=4,
        beds=4,
        bath=2,
        type="camping",
        clean_fee=8,
        service_fee=15,
        created=datetime.datetime(2022, 6, 20)
    ),
    Spot(
       address="provide later",
        city="Joshua Tree",
        state="California",
        country="United States",
        name="Casa Pequena - Ultimate Camping Vibes, Views",
        price=189,
        preview_img="https://a0.muscache.com/im/pictures/a8d10906-ed78-4167-9ba6-bacf9924a6f4.jpg?im_w=720",
        tags="entire place",
        userId=1,
        guests=4,
        bedroom=1,
        beds=2,
        bath=1,
        type="camping",
        clean_fee=2,
        service_fee=12,
        created=datetime.datetime(2022, 7, 20)
    ),
    Spot(
        address="provide later",
        city="Joshua Tree",
        state="California",
        country="United States",
        name="Joshua Tree Desert Retreat: Hot Tub, Game Room, National Park, Hammocks",
        price=373,
        preview_img="https://a0.muscache.com/im/pictures/5aac9457-55cc-4f9a-a084-b05dca92b44f.jpg?im_w=720",
        tags="entire home",
        userId=1,
        guests=8,
        bedroom=4,
        beds=4,
        bath=2,
        type="camping",
        clean_fee=8,
        service_fee=15,
        created=datetime.datetime(2022, 6, 20)
    ),
    Spot(
        address="provide later",
        city="Joshua Tree",
        state="California",
        country="United States",
        name="Joshua Tree Desert Retreat: Hot Tub, Game Room, National Park, Hammocks",
        price=373,
        preview_img="https://a0.muscache.com/im/pictures/cbd94c71-9592-4ec3-92e4-8360b2f38088.jpg?im_w=720",
        tags="entire place",
        userId=1,
        guests=8,
        bedroom=4,
        beds=4,
        bath=2,
        type="camping",
        clean_fee=8,
        service_fee=15,
        created=datetime.datetime(2022, 5, 20)
    ),
    Spot(
        address="provide later",
        city="Joshua Tree",
        state="California",
        country="United States",
        name="Modern Airstream near Joshua Tree National Park",
        price=185,
        preview_img="https://a0.muscache.com/im/pictures/c44a6dec-b585-4e6c-b0b1-2f92364bfa05.jpg?im_w=720",
        tags="entire home",
        userId=1,
        guests=2,
        bedroom=1,
        beds=1,
        bath=1,
        type="camping",
        clean_fee=7,
        service_fee=13,
        created=datetime.datetime(2022, 4, 20)
    ),
]

amazing_views = [
    Spot(
        address="provide later",
        city="Manhattan Beach",
        state="California",
        country="United States",
        name="The Glass Beach House on The Strand",
        price=1600,
        preview_img="https://a0.muscache.com/im/pictures/fc2644ca-be6e-40de-94a8-acfe7eb816c5.jpg?im_w=960",
        tags="entire home",
        userId=2,
        guests=6,
        bedroom=3,
        beds=3,
        bath=2,
        type="amazing views",
        clean_fee=11,
        service_fee=12,
        created=datetime.datetime(2022, 3, 20)
    ),
    Spot(
        address="provide later",
        city="Los Angeles",
        state="California",
        country="United States",
        name="The Glass Beach House on The Strand",
        price=790,
        preview_img="https://a0.muscache.com/im/pictures/8881fd27-6f30-4781-b91c-9c0c5e59a93f.jpg?im_w=720",
        tags="entire place",
        userId=2,
        guests=3,
        bedroom=1,
        beds=2,
        bath=1,
        type="amazing views",
        clean_fee=8,
        service_fee=15,
        created=datetime.datetime(2022, 2, 20)
    ),
    Spot(
        address="provide later",
        city="Marina del Rey",
        state="California",
        country="United States",
        name="RAD! SEA+ OCEAN View House @ Malibu boarder",
        price=599,
        preview_img="https://a0.muscache.com/im/pictures/cfbaf81b-28f4-4bd9-9eed-9fcb04c45eba.jpg?im_w=720",
        tags="entire home",
        userId=2,
        guests=7,
        bedroom=4,
        beds=4,
        bath=2,
        type="amazing views",
        clean_fee=9,
        service_fee=12,
        created=datetime.datetime(2022, 1, 20)
    ),
    Spot(
        address="provide later",
        city="Malibu",
        state="California",
        country="United States",
        name="WAVERLY BLACK BUNGALOW OVER THE WATER~~~",
        price=690,
        preview_img="https://a0.muscache.com/im/pictures/92e205c0-f16c-43c9-b65a-68fdc45053a6.jpg?im_w=720",
        tags="entire house",
        userId=2,
        guests=4,
        bedroom=1,
        beds=1,
        bath=1,
        type="amazing views",
        clean_fee=11,
        service_fee=12,
        created=datetime.datetime(2022, 10, 20)
    ),
    Spot(
        address="provide later",
        city="Malibu",
        state="California",
        country="United States",
        name="Malibu Mid-Century Modern Luxury retreat home",
        price=1875,
        preview_img="https://a0.muscache.com/im/pictures/febf3235-5166-4887-aac3-24b01ac5eec6.jpg?im_w=720",
        tags="entire home",
        userId=2,
        guests=8,
        bedroom=4,
        beds=5,
        bath=3,
        type="amazing views",
        clean_fee=5,
        service_fee=12,
        created=datetime.datetime(2022, 9, 20)
    ),
    Spot(
        address="provide later",
        city="Mulibu",
        state="California",
        country="United States",
        name="Malibu Charming GH, Mins Drive to Beach & Hike",
        price=190,
        preview_img="https://a0.muscache.com/im/pictures/28b9f895-ac96-48fc-aa68-a1a48c1e5099.jpg?im_w=720",
        tags="entire house",
        userId=2,
        guests=2,
        bedroom=1,
        beds=1,
        bath=1,
        type="amazing views",
        clean_fee=8,
        service_fee=12,
        created=datetime.datetime(2022, 6, 21)
    ),
    Spot(
        address="provide later",
        city="Malibu",
        state="California",
        country="United States",
        name="Stunning oceanfront beach house with balcony, grill, & fireplaces - snowbirds OK",
        price=1049,
        preview_img="https://a0.muscache.com/im/pictures/10c45738-edaa-4d65-865b-d9703676968a.jpg?im_w=1200",
        tags="entire house",
        userId=2,
        guests=8,
        bedroom=2,
        beds=4,
        bath=2,
        type="amazing views",
        clean_fee=6,
        service_fee=13,
        created=datetime.datetime(2022, 7, 10)
    ),
]

cabins = [
    Spot(
        address="provide later",
        city="Oakhurst",
        state="California",
        country="United States",
        name="Insta-worthy Nature Cabin w/Queen Bed by Yosemite",
        price=138,
        preview_img="https://a0.muscache.com/im/pictures/52ac4d52-1737-4c5d-81f4-d5b3e3160abf.jpg?im_w=1200",
        tags="entire place",
        userId=3,
        guests=2,
        bedroom=1,
        beds=1,
        bath=1,
        type="cabins",
        clean_fee=11,
        service_fee=15,
        created=datetime.datetime(2022, 7, 10)
    ),
    Spot(
        address="provide later",
        city="Ahwahnee",
        state="California",
        country="United States",
        name="Mtn top Cabin near Yosemite, sunset views, arcade",
        price=200,
        preview_img="https://a0.muscache.com/im/pictures/5847e992-2008-40c7-b363-a7ad65c3c410.jpg?im_w=720",
        tags="entire cabin",
        userId=3,
        guests=11,
        bedroom=3,
        beds=7,
        bath=3,
        type="cabins",
        clean_fee=25,
        service_fee=18,
        created=datetime.datetime(2022, 6, 10)
    ),
    Spot(
        address="provide later",
        city="Oakhurst",
        state="California",
        country="United States",
        name="Modern A-frame & in-law cabin Yosemite Oakhurst",
        price=374,
        preview_img="https://a0.muscache.com/im/pictures/ff132e6f-45df-4784-a75f-98c87cbb1f8e.jpg?im_w=720",
        tags="entire cabin",
        userId=3,
        guests=9,
        bedroom=5,
        beds=5,
        bath=2,
        type="cabins",
        clean_fee=11,
        service_fee=15,
        created=datetime.datetime(2022, 8, 20)
    ),
    Spot(
        address="provide later",
        city="Oakhurst",
        state="California",
        country="United States",
        name="Rustic River Creek Cabin/on the river/30min to YNP",
        price=129,
        preview_img="https://a0.muscache.com/im/pictures/e626171a-e02b-41d5-90cd-763f414bbbd0.jpg?im_w=720",
        tags="tiny home",
        userId=3,
        guests=2,
        bedroom=1,
        beds=1,
        bath=1,
        type="cabins",
        clean_fee=5,
        service_fee=1,
        created=datetime.datetime(2022, 9, 2)
    ),
    Spot(
        address="provide later",
        city="Oakhurst",
        state="California",
        country="United States",
        name="Casa Rio Yosemite -Waterfall plus 9 Acres",
        price=422,
        preview_img="https://a0.muscache.com/im/pictures/923a55e8-f3de-402b-b4ca-edd99a30ce7a.jpg?im_w=720",
        tags="entire home",
        userId=3,
        guests=14,
        bedroom=3,
        beds=9,
        bath=2,
        type="cabins",
        clean_fee=11,
        service_fee=18,
        created=datetime.datetime(2022, 8, 20)
    ),
    Spot(
        address="provide later",
        city="Mariposa",
        state="California",
        country="United States",
        name="The Lodge at Uli Pines by BnB Yosemite",
        price=202,
        preview_img="https://a0.muscache.com/im/pictures/ae964026-b300-4aa9-9891-871f162ce01e.jpg?im_w=1200",
        tags="entire home",
        userId=3,
        guests=8,
        bedroom=2,
        beds=3,
        bath=2,
        type="cabins",
        clean_fee=11,
        service_fee=15,
        created=datetime.datetime(2022, 7, 20)
    ),
    
]


def seed_spots():
    for s in spots:
        db.session.add(s)
    for s in camping:
        db.session.add(s)
    for s in amazing_views:
        db.session.add(s)
    for s in cabins:
        db.session.add(s)
    db.session.commit()


def undo_spots():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.spots RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM spots")
        
    db.session.commit()